version: "3"
networks:
  public:
#     ipam:
#       config:
#         - subnet: 192.168.2.0/24
services:
  api:
    container_name: hatypikhouse_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    networks:
      - public
    environment:
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_BLOCKLIST_ENABLED=${JWT_BLOCKLIST_ENABLED}
      - JWT_BLACKLIST_TOKEN_CHECKS=${JWT_BLACKLIST_TOKEN_CHECKS}
      - UPLOADED_IMAGES_DEST=${UPLOADED_IMAGES_DEST}
      # - APP_SECRET_KEY=${APP_SECRET_KEY}
      - SQLALCHEMY_DATABASE_URI=${SQLALCHEMY_DATABASE_URI}
      - MAILGUN_API_KEY=${MAILGUN_API_KEY}
      - FROM_EMAIL=${FROM_EMAIL}
      - MAILGUN_DOMAIN=${MAILGUN_DOMAIN}
      - GOOGLE_OAUTH_CLIENT_ID=${GOOGLE_OAUTH_CLIENT_ID}
      - GOOGLE_OAUTH_CLIENT_SECRET=${GOOGLE_OAUTH_CLIENT_SECRET}
      - GITHUB_COSUMMER_KEY=${GITHUB_COSUMMER_KEY}
      - GITHUB_COSUMMER_SECRET=${GITHUB_COSUMMER_SECRET}
      - FACEBOOK_CONSUMMER_KEY=${FACEBOOK_CONSUMMER_KEY}
      - FACEBOOK_CONSUMMER_SECRET=${FACEBOOK_CONSUMMER_SECRET}
      - STRIPE_ID_API=${STRIPE_ID_API}
      - STRIPE_API_PUBLIC_KEY=${STRIPE_API_PUBLIC_KEY}
      - STRIPE_API_SECRET_KEY=${STRIPE_API_SECRET_KEY}
      - SMPT_SERVER=${SMPT_SERVER}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_LOGIN=${SMTP_LOGIN}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - FROM_ADDR=${FROM_ADDR}
      - PROPAGATE_EXCEPTIONS=${PROPAGATE_EXCEPTIONS}
      - SESSION_TYPE=${SESSION_TYPE}
      - SECRET_KEY=${SECRET_KEY}
      - API_TITLE=${API_TITLE}
      - API_VERSION=${API_VERSION}
      - OPENAPI_VERSION=${OPENAPI_VERSION}
      - OPENAPI_URL_PREFIX=${OPENAPI_URL_PREFIX}
      - OPENAPI_SWAGGER_UI_PATH=${OPENAPI_SWAGGER_UI_PATH}
      - OPENAPI_SWAGGER_UI_URL=${OPENAPI_SWAGGER_UI_URL}
      - SQLALCHEMY_TRACK_MODIFICATIONS=${SQLALCHEMY_TRACK_MODIFICATIONS}
      - MAX_CONTENT_LENGTH=${MAX_CONTENT_LENGTH}
    volumes:
      - .:/app
    depends_on:
      - db
    # command: bash -c 'while ! nc -z db 3306; do sleep 1; done; python3 app.py'
  # test:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     command: ["pytest","test", "-v"]
  #   networks:
  #     - public
  #   environment:
  #     - JWT_SECRET_KEY=${JWT_SECRET_KEY}
  #     - JWT_BLOCKLIST_ENABLED=${JWT_BLOCKLIST_ENABLED}
  #     - JWT_BLACKLIST_TOKEN_CHECKS=${JWT_BLACKLIST_TOKEN_CHECKS}
  #     - UPLOADED_IMAGES_DEST=${UPLOADED_IMAGES_DEST}
  #     - APP_SECRET_KEY=${APP_SECRET_KEY}
  #     - SQLALCHEMY_DATABASE_URI=${SQLALCHEMY_DATABASE_URI}
  #     - MAILGUN_API_KEY=${MAILGUN_API_KEY}
  #     - FROM_EMAIL=${FROM_EMAIL}
  #     - MAILGUN_DOMAIN=${MAILGUN_DOMAIN}
  #     - GOOGLE_OAUTH_CLIENT_ID=${GOOGLE_OAUTH_CLIENT_ID}
  #     - GOOGLE_OAUTH_CLIENT_SECRET=${GOOGLE_OAUTH_CLIENT_SECRET}
  #     - GITHUB_COSUMMER_KEY=${GITHUB_COSUMMER_KEY}
  #     - GITHUB_COSUMMER_SECRET=${GITHUB_COSUMMER_SECRET}
  #     - FACEBOOK_CONSUMMER_KEY=${FACEBOOK_CONSUMMER_KEY}
  #     - FACEBOOK_CONSUMMER_SECRET=${FACEBOOK_CONSUMMER_SECRET}
  #     - STRIPE_ID_API=${STRIPE_ID_API}
  #     - STRIPE_API_PUBLIC_KEY=${STRIPE_API_PUBLIC_KEY}
  #     - STRIPE_API_SECRET_KEY=${STRIPE_API_SECRET_KEY}
  #     - SMPT_SERVER=${SMPT_SERVER}
  #     - SMTP_PORT=${SMTP_PORT}
  #     - SMTP_LOGIN=${SMTP_LOGIN}
  #     - SMTP_PASSWORD=${SMTP_PASSWORD}
  #     - FROM_ADDR=${FROM_ADDR}
  #     - PROPAGATE_EXCEPTIONS=${PROPAGATE_EXCEPTIONS}
  #     - SESSION_TYPE=${SESSION_TYPE}
  #     - SECRET_KEY=${SECRET_KEY}
  #     - API_TITLE=${API_TITLE}
  #     - API_VERSION=${API_VERSION}
  #     - OPENAPI_VERSION=${OPENAPI_VERSION}
  #     - OPENAPI_URL_PREFIX=${OPENAPI_URL_PREFIX}
  #     - OPENAPI_SWAGGER_UI_PATH=${OPENAPI_SWAGGER_UI_PATH}
  #     - OPENAPI_SWAGGER_UI_URL=${OPENAPI_SWAGGER_UI_URL}
  #     - SQLALCHEMY_TRACK_MODIFICATIONS=${SQLALCHEMY_TRACK_MODIFICATIONS}
  #     - MAX_CONTENT_LENGTH=${MAX_CONTENT_LENGTH}
  #   volumes:
  #     - .:/app
  #   stdin_open: true
  #   tty:true
  #   depends_on:
  #     - db
  db:
    container_name: hatypikhouse_db
    image: mysql:latest
    env_file:
      - .env
    ports:
      - 3307:3306
    networks:
      - public
    restart: always
    # container_name: db
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
